Algoritmo "Questão 07"
// Fazer um algoritmo que pergunte 3 números
//e apresente a média aritmética entre estes 3 números.
Var
media:real
valor1,valor2,valor3:real
Inicio
escreva (" Escolha valor 1:")
leia (valor1)

escreva (" Escolha valor 2:")
leia (valor2)

escreva (" Escolha valor 3:")
leia (valor3)

media <-(valor1+valor2+valor3)/3

escreva ("Aqui está sua média aritmética", media)

Fimalgoritmo