Algoritmo "Questão 09"
// Fazer um algoritmo que pergunte 1 número e apresente:
//a) O próprio número
//b) O quadrado deste número
//c) A raiz quadrada deste número
Var
valor,valor2,valor3:real
Inicio
escreval("Me informe um valor:")
leia (valor)

escreval("Aqui está o seu valor:",valor)

valor2 <- (valor^2);

escreval("Aqui está o quadrado do seu valor:",valor2)

valor3 <- RaizQ(valor);

escreval("Aqui está a raiz quadrada do seu valor:",valor3)

Fimalgoritmo