Algoritmo "Questão 03"
// Disciplina   :  Lógica de Programação 
// Professor   : Fabricio Curvello 
// Fazer um programa que pergunte um valor em Dólares
// e apresente o equivalente em Reais. Considere U$1,00 = R$1,72
Var
// Seção de Declarações das variáveis
Dol: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Me informe um valor em Dolares para a conversão da moeda:")
leia(dol)

escreval (dol, "dólares = ", (dol * 1.72 ), " reais ")
Fimalgoritmo